### ISSUE TITLE
AVS Notification Support

### ISSUE THREAD

**Issue by gdgeist** [openhab/openhab-alexa#140] opened 2019-02-17 00:04 UTC
AVS service allows Notifications.  While audible notifications through the speech channel or amazonechocontrol binding are available - visual notifications in line with what the Amazon Echo ecosystem offers simplifies a path to visual notifications.  ESP/Arduino  MQTT based homegrown solutions aside most with this binding active would use this feature.

**Comment by digitaldan** [comment] 2019-02-17 00:34
This is a Duplicate of #49 .  If we want to re-open that, then that's ok, but let's not create another issue.

**Closed by digitaldan** 2019-02-17 00:34 UTC
Labels: duplicate
