### ISSUE TITLE
[V3] Can't discover device if one item in group has no alexa tag

### ISSUE THREAD

**Issue by lukeIam** [openhab/openhab-alexa#83] opened 2018-08-23 18:09 UTC
I'm using the V3-version of the skill (with aws lambda and nginx-tunnel to my openhab instance).
Everything is working fine, but as soon as a add an item without an `{ alexa=... }` tag, the device can not be discovered.

**Works (device can be discovered):**
```
Group gFernseher "Fernseher" (gWohnzimmer) { alexa="Endpoint.TV" }
Switch Wohnzimmer_Fernseher_AnAus "AnAus" <switch> (gFernseher) { alexa="PowerController.powerState" }
```

**Does not work  (device can't be discovered):**
```
Group gFernseher "Fernseher" (gWohnzimmer) { alexa="Endpoint.TV" }
Switch Wohnzimmer_Fernseher_AnAus "AnAus" <switch> (gFernseher) { alexa="PowerController.powerState" }
Switch Wohnzimmer_Fernseher_Stero_Strom <switch> (gFernseher)
```

Is this a wanted behavior? Is there something like `alexa=Ignore`?
For now I'm just creating two groups: one with alexa only items and one with all.

**Comment by jsetton** [comment] 2018-09-18 16:02
@lukeIam Which V3 version are you using? Do you see any errors in the AWS Lambda logs?

**Comment by lukeIam** [comment] 2018-10-16 16:56
@jsetton 

sorry for the late answer - is there an version tag somewhere in the code? (as far is I can remember I set up the system with the lastest V3 somewhere in July)

**Comment by digitaldan** [comment] 2018-10-16 19:35
This is by design, all items need to map to a Alexa type, we don't try and guess what the alxea type is when using V3 tags, so if you have a Number, this could be Alexa.PercentageController or Alexa.BrightnessController, but we can't guess what that would be.  A switch would be easier to guess, but would be inconsistent if this was an exception

**Comment by lukeIam** [comment] 2018-10-19 12:52
> You would have to go by the git repository URL, branch name and last commit version you pulled in your local repository.

Unfortunately, I do not longer have the cloned repo locally (new pc) :/
 
> Do you still have the same issue and is there any errors in your AWS Lambda function logs?

At the moment I have an other problem with certificate renewal (and no time to fix it) - so I can't test at the moment...

> This is by design, all items need to map to a Alexa type, we don't try and guess what the alxea type is when using V3 tags, so if you have a Number, this could be Alexa.PercentageController or Alexa.BrightnessController, but we can't guess what that would be. A switch would be easier to guess, but would be inconsistent if this was an exception

Sure - guessing is not the best idea, but why not ignoring items without tag? Or at least an option to manually ignore items (e.g `Alex.ignore` or `Alexa.nothing`). Then we can reuse the normal OH group even if it has more items than Alexa can use.

**Comment by lukeIam** [comment] 2018-10-19 13:06
> You would have to go by the git repository URL, branch name and last commit version you pulled in your local repository.

Unfortunately, I do not longer have the local repo clone (new pc)

> Do you still have the same issue and is there any errors in your AWS Lambda function logs?

At the moment I have an problem with certificate renewal (and no time to look after it) - so I can't test.

> This is by design, all items need to map to a Alexa type, we don't try and guess what the alxea type is when using V3 tags, so if you have a Number, this could be Alexa.PercentageController or Alexa.BrightnessController, but we can't guess what that would be. A switch would be easier to guess, but would be inconsistent if this was an exception

Sure guessing the right type might not be the best option. But why not ignoring items with out tag.
Or introduce an ignore tag to label an item as not used in the skill?
Otherwise I can't reuse my existing groups and have to create additional ones only for the alexa skill.

**Comment by jsetton** [comment] 2018-10-20 03:43
@lukeIam once you resolved your certificate issue, can you also get the latest v3 version and see if you are experiencing this issue? I was unable to replicate on my side unless I am missing something.

For the example you provided above, that you marked as not working, are you saying that the group endpoint is not discovered at all? Maybe if you explicitly mentioned what your expectation is using the item example you provided. Anyway, items without tags or metadata configuration should be ignored.

**Comment by lukeIam** [comment] 2018-11-01 17:35
> For the example you provided above, that you marked as not working, are you saying that the group endpoint is not discovered at all?

yes, it's not discovered at all -> "No devices found"

> Maybe if you explicitly mentioned what your expectation is using the item example you provided.

A (discoverable) device with the name "Fernseher" and if I tell Alexa to turn it on or off the switch "Wohnzimmer_Fernseher_AnAus" should be updated. "Wohnzimmer_Fernseher_Stero_Strom" should be ignored.

> @lukeIam once you resolved your certificate issue, can you also get the latest v3 version and see if you are experiencing this issue? I was unable to replicate on my side unless I am missing something.

From the AWS Log:

```
2018-11-01T17:29:08.172Z	a2a87a2e-ddfb-11e8-a51c-11b9b75be9e1	TypeError: Cannot read property 'alexa' of undefined
at Object.metadataToPropertyMap (/var/task/utils.js:159:16)
at /var/task/ohConnectorV3.js:704:35
at Array.forEach (native)
at /var/task/ohConnectorV3.js:701:26
at Array.forEach (native)
at /var/task/ohConnectorV3.js:695:46
at Array.forEach (native)
at /var/task/ohConnectorV3.js:674:11
at IncomingMessage.<anonymous> (/var/task/rest.js:90:17)
at emitNone (events.js:91:20)
```

**Comment by fmeies** [comment] 2018-11-02 07:54
In ohConnectorV3.js, discoverDevices() we make the assumption, that any member of an "endpoint group" has to have a metadata property. It would be pretty easy to simply skip the ones without a metadata property:

```diff
diff --git a/ohConnectorV3.js b/ohConnectorV3.js
index 00117e3..a1d9b41 100644
--- a/ohConnectorV3.js
+++ b/ohConnectorV3.js
@@ -699,9 +699,11 @@ function discoverDevices() {
             log.debug("found group " + groupMatch[0] + " for item " + item.name);
             isEndpointGroup = true;
             item.members.forEach(function (member) {
-              log.debug("adding  " + member.name + " to group " + item.name);
-              groupItems.push(member.name);
-              propertyMap = utils.metadataToPropertyMap(member, propertyMap);
+              if(typeof(member.metadata) !== 'undefined') {
+                log.debug("adding  " + member.name + " to group " + item.name);
+                groupItems.push(member.name);
+                propertyMap = utils.metadataToPropertyMap(member, propertyMap);
+              }
             });
             //set display category for group
             addDisplayCategory(groupMatch[1].toUpperCase());
```

**Comment by digitaldan** [comment] 2019-02-02 23:54
thanks @fmeies  for the fix.

**Comment by digitaldan** [comment] 2019-02-03 01:36
Then i was a bit hasty in the fix, I'll reopen and take a look. Feel free to open a PR as well.  Thanks!

**Comment by jsetton** [comment] 2019-02-03 01:40
No worries. I actually had plans to do some more work based on our discussion in November. I will try to submit PRs this week.

**Comment by digitaldan** [comment] 2019-02-03 19:05
Awesome.  FYI,  I am going to focus on getting v3 out the door, so I am planning on being much more active from here on out.

**Comment by digitaldan** [comment] 2019-02-13 17:05
@jsetton Do you have time for a PR or would you like me to work on this?

**Comment by jsetton** [comment] 2019-02-13 17:08
I do. Sorry I have been working on other projects. I am also trying to extract some of the enhancements I made in my last PR which aren't related to the async implementation. That's why it is taking more time. Anyway, I will try to get you something by tomorrow.

**Comment by digitaldan** [comment] 2019-02-13 17:09
No worries, thanks!

**Comment by jsetton** [comment] 2019-02-16 03:53
Sorry for the delay. I finally got around to submitting that one.

**Closed** 2019-02-18 00:34 UTC
Labels: bug
