### ISSUE TITLE
number items of e.g. TargetTemperature are wrong

### ISSUE THREAD

**Issue by codefalk** [openhab/openhab-alexa#18] opened 2017-03-23 10:31 UTC
When setting command of e.g. "set numberitem to 4", the skill responds with numberitem=3. 
There is the same issue with the hue emulation. The (hue emulation)-issue has been described [here ](https://homematic-forum.de/forum/viewtopic.php?f=64&t=33601&start=110#p336721)as well.

Even though there is a workaround by just adding 1 to the value with a rule, problem with this issue is that there is no chance to distinguish between value "1" and "OFF" since both lead to a response of "0".

**Comment by ami2009** [comment] 2017-04-20 09:32
I try to control KNX-scenes with this and have the same issue/bug. 

I cannot distinguish between "0"/"OFF" and "1" since all values between 1 and 99 are subtracted by 1, but the values values 0/OFF and 100/ON are correct. 

Example:

ITEM:
Number szeneWohnzimmer  "Wohnzimmerlicht" <light> [" Lighting "]

RULE:
rule "szeneWohnzimmerChanged"
when 
	Item szeneWohnzimmer changed 
then
	switch (szeneWohnzimmer.state as DecimalType).intValue {
		// schalten
		case 0:	schalteGruppeAus.apply(szgWohnzimmer)
		case 1:	schalteGruppeStatus.apply(szgWohnzimmer, szcWohnzimmerI)
		case 2:	schalteGruppeStatus.apply(szgWohnzimmer, szcWohnzimmerII)
		case 3:	schalteGruppeStatus.apply(szgWohnzimmer, szcWohnzimmerIII)

		// lernen
		case 11: speicherGruppeStatus.apply(szgWohnzimmer, szcWohnzimmerI)
		case 12: speicherGruppeStatus.apply(szgWohnzimmer, szcWohnzimmerII)
		case 13: speicherGruppeStatus.apply(szgWohnzimmer, szcWohnzimmerIII)

		default: return false		
	}
	
    Thread::sleep(500)
	postUpdate(szeneWohnzimmer, 99)
end

**Comment by digitaldan** [comment] 2017-04-27 17:28
So I am not able to reproduce this.  If I say "set lights to x" my openhab receives x .  Can you confirm this is still the case?  

@ami2009  your rule is depending on a state change, can you instead respond to the actual command like
`when 
	Item szeneWohnzimmer received command 
then`
and then use the `receivedCommand` variable instead of state?  Maybe print out what the command is? I have noticed that if I say "set item to 0" that alexa sends the command "0"  but OH is setting it to 1, not sure why.

**Comment by codefalk** [comment] 2017-05-01 20:59
Yes, i still confirm the behavior, but I also did not change any thing. Version is OH2 Release. 
When I say " set Fernseher to 3" (checked in the Alexa app) the log sais:
` Item 'TV_Control_Set' received command 2`
The item is defined as 
`Number	TV_Control_Set "Fernseher" (gTV_Control) [ "TargetTemperature" ]`

To make sure, I also changed languages and tried the same with English (US). No changes.

**Comment by codefalk** [comment] 2017-05-19 21:38
Update: The problem is probably not the Alexa skill itself:
I just found out that my Alexa skill configuration works with Hue Emulation enabled only. This could lead to the Hue Emulation issue described earlier causing the problem (initial post).

My new issue is the Alexa skill not detecting devices without the Hue Emulation service being enabled ... but this is another discussion thread ...

**Comment by digitaldan** [comment] 2017-05-27 22:55
I am closing this as I do not think this is an alexa smart home skill issues, but rather a  hue emulator binding issue..

**Closed by digitaldan** 2017-05-27 22:55 UTC
Labels: bug
