### ISSUE TITLE
(German) Grammatical problem increasing/decreasing temperature by 1 degree

### ISSUE THREAD

**Issue by cubistico** [openhab/openhab-alexa#127] opened 2019-02-11 14:43 UTC
This applies to using Alexa in German.

The command does not work:
"Alexa, erhöhe die Temperatur von Wohnzimmer um ein Grad"
Alexa replies:
"Dieser Befehl funktioniert für das Gerät Wohnzimmer nicht"

However, this works:
"Alexa, erhöhe die Temperatur von Wohnzimmer um **eins** Grad"

Obviously, the word "ein" is not accepted as a number, only "eins" is, but that's not natural language. Same effect when decreasing.

**Comment by Flole998** [comment] 2019-02-11 17:49
Not a bug in the skill, you should submit this issue report to amazon directly as they take care of all the processing and especially the voice recognition.

I just checked and I am having the same issue and will report it aswell.

**Comment by cubistico** [comment] 2019-02-11 17:57
Thanks. Could you provide a link where I can report the issue?

**Comment by Flole998** [comment] 2019-02-11 18:04
That would be here:  https://www.amazon.de/gp/help/customer/contact-us/

Click on devices, select an Echo device, then choose "Alexa Voice Services" and in the next Menu "Smart Home". You can either contact them by phone or by chat. If you could give me a little update on what the response was I'll appreciate it. Depending on what they say I can try to directly forward it to the appropriate developer team.

**Comment by digitaldan** [comment] 2019-02-12 05:30
Can this issue be closed?

**Comment by cubistico** [comment] 2019-02-12 10:03
> If you could give me a little update on what the response was I'll appreciate it. Depending on what they say I can try to directly forward it to the appropriate developer team.

They advised me to provide feedback in the Alexa app > Preferences > Alexa account, then select the problem command. Answer the question "Did Alexa do what you wanted" with "No". However, it's not possible to add any detail information from there.

Additionally, the support staff told me they will forward the report to their developers and keep me updated about the progress.

> Can this issue be closed?

Well, it's still an issue, though obviously not in the skill. You decide how to handle this!

**Comment by digitaldan** [comment] 2019-02-12 14:52
I’ll close it Since this is not something we can fix, and not something we can workaround

**Closed by digitaldan** 2019-02-12 14:52 UTC
